up:
	docker-compose up -d
down:
	docker-compose down
build:
	docker-compose build
ps:
        docker-copose ps
php:
	docker exec -it backend_app_1 bash
mysql:
	docker exec -it backend_mysql_1 bash
web:
        docker exec -it backend_web_1 bash

# 本番用
prod_up:
        docker compose up -d
prod_down:
        docker compose down
prod_build:
        docker compose build
prod_ps:
        docker compose ps
prod_php:
        docker exec -it backend-app-1 bash
prod_mysql:
        docker exec -it backend-mysql-1 bash
prod_web:
        docker exec -it backend-web-1 bash
