openapi: 3.1.0
info:
  title: もくもくMAPのAPI設計書
  description: |-
    # 本アプリケーションで使用するAPIの内容を記載

  version: 1.0.0
servers:
  - url: http://localhost:8000/api/

paths:
  # ログインAPI
  login/:
    post:
      tags:
        - login
      summary: ログインAPI
      description: アプリケーションにログインする
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: メールアドレス
                  example: "test@gmail.com"
                password:
                  type: string
                  description: パスワード
                  example: "password"
              required:
                - "email"
                - "password"
      responses:
        "200":
          description: ログインに成功
          content:
            application/json:
              schema:
                type: object
              example:
                message: "ログインに成功しました。"
        "401":
          description: ログインに失敗
          content:
            application/json:
              schema:
                type: object
              example:
                message: "メールアドレスまたはパスワードが間違っています"
