openapi: 3.1.0
info:
  title: もくもくMAPのAPI設計書
  description: |-
    # 本アプリケーションで使用するAPIの内容を記載

  version: 1.0.0
servers:
  - url: http://localhost:8000/api/

paths:
  # ログインAPI
  login/:
    post:
      tags:
        - ログインAPI
      description: アプリケーションにログインする
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: メールアドレス
                  example: "test@gmail.com"
                password:
                  type: string
                  description: パスワード
                  example: "password"
              required:
                - "email"
                - "password"
      responses:
        "200":
          description: ログインに成功
          content:
            application/json:
              schema:
                type: object
              example:
                message: "ログインに成功しました。"
        "401":
          description: ログインに失敗
          content:
            application/json:
              schema:
                type: object
              example:
                message: "メールアドレスまたはパスワードが間違っています"
  # ログアウトAPI
  logout/:
    post:
      tags:
        - ログアウトAPI
      description: アプリケーションをログアウトさせる
      responses:
        "200":
          description: ログアウトに成功
          content:
            application/json:
              schema:
                type: object
              example:
                message: "ログアウトが完了しました。"
  # 登録API
  register/:
    post:
      tags:
        - ユーザー登録API
      description: アプリケーションにユーザー登録する
      requestBody:
         content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: ユーザー名
                    maxLength: 255
                    minLength: 1
                    example: "山田太郎"
                  email:
                    type: string
                    description: メールアドレス
                    maxLength: 255
                    minLength: 1
                    format: email
                    example: "test@gmai.com"
                  password:
                    type: string
                    description: パスワード
                    maxLength: 255
                    minLength: 8
                    example: "password"
                  birthday:
                    type: string
                    description: 生年月日
                    format: date
                    nullable: true
                    example: "1998-12-26"
                  pref_id:
                    type: integer
                    description: 都道府県ID
                    example: 1
                  introduction:
                    type: string
                    description: 自己紹介
                    maxLength: 1000
                    nullable: true
                    example: "こんにちは"
                  twitter_url:
                    type: string
                    description: TwitterのURL
                    format: url
                    maxLength: 255
                    nullable: true
                    example: "https://twitter/example.com"
                required:
                  - name
                  - email
                  - password
                  - pref_id
      responses:
        "200":
          description: ユーザー登録完了
          content:
            application/json:
              schema:
                type: object
              example:
                message: "ユーザー登録が完了しました。"
        "422":
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
              example:
                message: "名前を入力してください"

# ログインユーザ情報編集API
  /update_auth/{auth_id}:
    post:
      tags:
        - ログインユーザ情報編集API
      description: ログインユーザ情報を更新する
      parameters:
        - name: "auth_id"
          in: "path"
          schema:
            type: "integer"
          description: "ログインユーザのID"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                  description: ユーザー名
                  maxLength: 255
                  minLength: 1
                  example: "山田太郎"
                email:
                  type: string
                  description: メールアドレス
                  maxLength: 255
                  minLength: 1
                  format: email
                  example: "test@gmai.com"
                birthday:
                  type: string
                  description: 生年月日
                  format: date
                  nullable: true
                  example: "1998-12-26"
                pref_id:
                  type: integer
                  description: 都道府県ID
                  example: 1
                introduction:
                  type: string
                  description: 自己紹介
                  maxLength: 1000
                  nullable: true
                  example: "こんにちは"
                twitter_url:
                  type: string
                  description: TwitterのURL
                  format: url
                  maxLength: 255
                  nullable: true
                  example: "https://twitter/example.com"
              required:
                  - name
                  - email
                  - password
                  - pref_id
      responses:
        '200':
          description: "Successfully updated the user information."
          content:
            application/json:
              schema:
                type: "object"
              example:
                message: "編集が完了しました。"
        "422":
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
              example:
                message: "名前を入力してください"
# ログインユーザ情報取得API
  /get_auth:
    get:
      tags:
        - ログインユーザ情報取得API
      responses:
        '200':
          description: ログインユーザー情報を取得する
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                        description: ユーザーのID
                        example: 1
                      name:
                        type: string
                        description: ユーザー名
                        example: "山田太郎"
                      email:
                        type: string
                        format: email
                        description: ユーザーのメールアドレス
                        example: "test@gmail.com"
                      pref_id:
                        type: integer
                        format: int64
                        description: ユーザーが住む都道府県のID
                        example: 1
                      birthday:
                        type: string
                        format: date
                        description: ユーザーの生年月日
                        example: "1998-12-26"
                      introduction:
                        type: string
                        description: ユーザーの自己紹介
                        example: "こんにちは"
                      twitter_url:
                        type: string
                        format: url
                        description: ユーザーのTwitterのURL
                        example: "https://twitter/example.com"
                      old:
                        type: integer
                        format: int32
                        description: ユーザーの年齢
                        example: 25
                      pref_name:
                        type: string
                        description: ユーザーが住む都道府県名
                        example: 東京都
                      image:
                        type: string
                        format: binary
                        description: ユーザーの画像
                        example: test_image.jpg
# パスワードリセット用メール送信API
  /send_email:
    post:
      tags:
        - パスワードリセット用メール送信API
      description: 指定されたメールアドレスにパスワード送信用のメールアドレスを送信する
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: "string"
                  format: "email"
                  description: "メールアドレス"
                  example: "test@gmai.com"
                  required: true
      responses:
        '200':
          description: "メール送信完了"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "メールを送信しました。"
        '400':
          description: "無効なユーザー、もしくは無効なトークンが検出された場合のエラー"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example:
                      - "無効なユーザーです。"
                      - "無効なトークンです。"
        "422":
          description: バリデーションエラー
          content:
            application/json:
              schema:
                type: object
              example:
                message: "メールアドレスを入力してください。"

# パスワード更新API
  /reset_password:
    post:
      tags:
        - パスワード更新API
      description: パスワードを更新する
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                password:
                  type: "string"
                  description: "パスワード"
                  min: 8
                  max: 255
                password_confirm:
                  type: "string"
                  description: "パスワード(更新用)"
                  min: 8
                  max: 255
                  same: "password"
                email:
                  type: string
                  format: email
                  description: ユーザーのメールアドレス
                  example: "test@gmail.com"
                token:
                  type: "string"
                  description: "パスワード更新用トークン。更新用のメールに含まれている"
              required:
                  - password
                  - password_confirm
      responses:
        '200':
          description: "パスワード更新完了"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "パスワードの変更が完了しました。"
        '400':
          description: "無効なユーザー、もしくは無効なトークンが検出された場合のエラー"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example:
                      - "無効なユーザーです。"
                      - "無効なトークンです。"
# もくもく会作成API
  /party/register:
    put:
      tags:
        - もくもく会作成API
      description: もくもく会を作成する
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                theme:
                  type: "string"
                  max: 30
                  description: "もくもく会の題名"
                  exists: "prefs,id"
                  example: "Laravel勉強会"
                introduction:
                  type: "string"
                  max: 1000
                  description: "もくもく会の詳細"
                  example: "LaravelのMVCの概念をを実際にアプリケーションの開発を行いながら学んでいきましょう!"
                pref_id:
                  type: "integer"
                  description: "都道府県ID"
                  exists: "prefs,id"
                  example: 1
                place:
                  type: "string"
                  max: 255
                  description: "もくもく会の開催場所"
                  example: "第一会議室"
                due_max:
                  type: "integer"
                  description: "もくもく会の参加上限人数"
                  example: 20
                due_date:
                  type: "string"
                  format: "date"
                  description: "もくもく会の参加期限"
                  after: "today"
                  example: "2023-12-26"
                tag_ids:
                  type: "array"
                  items:
                    type: "integer"
                    exists: "tags,id"
                  maxItems: 3
                  description: "タグIDの配列"
                  nullable: true
                  example: [1, 2, 3]
              required:
                  - theme
                  - introduction
                  - pref_id
                  - place
                  - due_max
                  - due_date
      responses:
        '200':
          description: "もくもく会作成完了"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "もくもく会の作成が完了しました。"
        '422':
          description: "バリデーションエラー"
          content:
            application/json:
              schema:
                type: "object"
                example:
                  error:
                      'theme.required': "題名を入力してください。"
                      'theme.string': "題名は文字列で入力してください。"
                      'theme.max': "題名は30文字以内で入力してください。"
                      'introduction.required': "詳細を入力してください。"
                      'introduction.max': "詳細は1000文字以内で入力してください。"
                      'pref_id.required': "都道府県を選択してください。"
                      'pref_id.exists': "指定された都道府県は存在しません。"
                      'place.required': "開催場所を入力してください。"
                      'place.max': "開催場所は255文字以内で入力してください。"
                      'due_max.required': "定員を選択してください。"
                      'due_date.required': "開催日時を入力してください。"
                      'due_date.after': "開催日時は明日以降にしてください。"
                      'tag_ids.max': "タグの選択は3つまでです。"
                      'tag_ids.*.exists': "存在しないタグが含まれています。"
